const SAVE_KEY='fcc_prep_saved_session_v1';
let BANK=[];let quiz=[];let index=0;let correct=0;let requestedCount=0;let currentMode='study';let markedQuestions=new Set();let answeredQuestions=new Set();let userAnswers=new Map();let reviewIndexes=[];let reviewIndex=0;
function shuffle(arr){return[...arr].sort(()=>Math.random()-.5)}
function getSelectedPool(){const e=document.getElementById('element').value;return BANK.filter(q=>e==='all'||q.element===e)}
function getSelectedElementLabel(){const s=document.getElementById('element');return s.options[s.selectedIndex].text}
function setSetupVisible(visible){const setup=document.querySelector('.setup-card:not(#resumeBox)');const resume=document.getElementById('resumeBox');const status=document.getElementById('questionStatus');if(setup)setup.style.display=visible?'block':'none';if(resume&&visible)updateResumeBox();if(resume&&!visible)resume.style.display='none';if(status)status.style.display=visible?'block':'none'}
function updateQuestionStatus(){const status=document.getElementById('questionStatus');if(!BANK.length){status.innerText='Loading questions...';return}const selectedPool=getSelectedPool();status.innerText=`${getSelectedElementLabel()}: ${selectedPool.length} questions available (${BANK.length} total loaded)`}
async function initApp(){const status=document.getElementById('questionStatus');try{BANK=await loadQuestionPool();updateQuestionStatus();document.getElementById('startBtn').disabled=false;updateResumeBox()}catch(error){console.error(error);status.innerText='Question data failed to load.'}}
function buildQuizPool(pool,count){if(!pool.length)return[];let output=[];while(output.length<count)output=output.concat(shuffle(pool));return output.slice(0,count)}
function startQuiz(){if(!BANK.length){alert('Question data is still loading. Please try again.');return}requestedCount=parseInt(document.getElementById('count').value,10)||35;currentMode=document.getElementById('mode').value;quiz=buildQuizPool(getSelectedPool(),requestedCount);index=0;correct=0;markedQuestions=new Set();answeredQuestions=new Set();userAnswers=new Map();reviewIndexes=[];reviewIndex=0;showQuiz()}
function startCustomQuiz(questionList,mode='test'){if(!questionList.length)return;quiz=shuffle(questionList);requestedCount=quiz.length;currentMode=mode;index=0;correct=0;markedQuestions=new Set();answeredQuestions=new Set();userAnswers=new Map();reviewIndexes=[];reviewIndex=0;showQuiz()}
function showQuiz(){setSetupVisible(false);document.getElementById('results').style.display='none';document.getElementById('quiz').style.display='grid';document.getElementById('sidebarTitle').innerText=`${quiz.length} questions`;document.getElementById('scoreLine').style.display=currentMode==='study'?'flex':'none';updateLegend();renderQuestion()}
function getQuestionKey(q){return q.id||`${q.element}-${q.question}`}
function isMarkedCurrent(){return quiz.length&&markedQuestions.has(getQuestionKey(quiz[index]))}
function canMoveNext(){return answeredQuestions.has(index)||isMarkedCurrent()}
function updateLegend(){const legend=document.querySelector('.legend');if(!legend)return;if(currentMode==='test'){legend.innerHTML='<div><span class="dot unanswered"></span>Unanswered</div><div><span class="dot answered-dot"></span>Answered</div><div><span class="dot marked-dot"></span>Marked</div>';return}legend.innerHTML='<div><span class="dot unanswered"></span>Unanswered</div><div><span class="dot correct-dot"></span>Correct</div><div><span class="dot incorrect-dot"></span>Incorrect</div><div><span class="dot marked-dot"></span>Marked</div>'}
function updateSidebar(){const nav=document.getElementById('questionNav');nav.innerHTML='';quiz.forEach((q,i)=>{const key=getQuestionKey(q);const btn=document.createElement('button');btn.className='nav-question';btn.innerText=`Question ${i+1}`;if(i===index)btn.classList.add('current');if(markedQuestions.has(key))btn.classList.add('marked');if(answeredQuestions.has(i)){if(currentMode==='study')btn.classList.add(userAnswers.get(i)===q.answer?'answered-correct':'answered-incorrect');else btn.classList.add('answered')}btn.onclick=()=>{index=i;renderQuestion()};nav.appendChild(btn)});const answered=answeredQuestions.size;const remaining=quiz.length-answered;const score=answered?Math.round(correct/answered*100):0;document.getElementById('answeredCount').innerText=answered;document.getElementById('remainingCount').innerText=remaining;document.getElementById('markedCount').innerText=markedQuestions.size;document.getElementById('sidebarScore').innerText=answered?`${score}%`:'--'}
function updateLiveScore(){const liveScore=document.getElementById('liveScore');if(currentMode!=='study'){liveScore.innerText='';return}const answered=answeredQuestions.size;const pct=answered?Math.round(correct/answered*100):0;liveScore.innerText=answered?`Study score: ${pct}% (${correct}/${answered}) - ${pct>=74?'PASSING':'NOT PASSING'}`:'Study score: no answers yet'}
function renderQuestion(){const q=quiz[index];const key=getQuestionKey(q);document.getElementById('progress').innerText=`Question ${index+1} of ${quiz.length}`;document.getElementById('qid').innerText=q.id;document.getElementById('question').innerText=q.question;const options=document.getElementById('options');options.innerHTML='';['A','B','C','D'].forEach(letter=>{const row=document.createElement('button');row.className='answer-row';row.innerHTML=`<span class="answer-letter">${letter}</span><span>${q.options[letter]}</span>`;if(answeredQuestions.has(index)){row.disabled=true;const selected=userAnswers.get(index);if(letter===selected)row.classList.add('selected-answer');if(currentMode==='study'){if(letter===q.answer)row.classList.add('correct');if(letter===selected&&selected!==q.answer)row.classList.add('wrong')}}row.onclick=()=>answerQuestion(letter,row,q);options.appendChild(row)});document.getElementById('markBtn').innerText=markedQuestions.has(key)?'Unmark':'Mark';document.getElementById('prevBtn').disabled=index===0;document.getElementById('nextBtn').disabled=!canMoveNext();updateSidebar();updateLiveScore();saveSession(false)}
function answerQuestion(letter,btn,q){if(answeredQuestions.has(index))return;answeredQuestions.add(index);userAnswers.set(index,letter);if(letter===q.answer)correct++;document.querySelectorAll('.answer-row').forEach(x=>x.disabled=true);btn.classList.add('selected-answer');if(currentMode==='study'){if(letter===q.answer)btn.classList.add('correct');else{btn.classList.add('wrong');document.querySelectorAll('.answer-row').forEach(x=>{if(x.innerText.trim().startsWith(q.answer))x.classList.add('correct')})}}document.getElementById('nextBtn').disabled=false;updateSidebar();updateLiveScore();saveSession(false)}
function toggleMarkedQuestion(){const q=quiz[index];const key=getQuestionKey(q);if(markedQuestions.has(key))markedQuestions.delete(key);else markedQuestions.add(key);renderQuestion();saveSession(false)}
function previousQuestion(){if(index<=0)return;index--;renderQuestion()}
function nextQuestion(){if(!canMoveNext())return;index++;if(index>=quiz.length){finishQuiz();return}renderQuestion()}
function saveSession(showAlert=true){if(!quiz.length)return;const session={savedAt:new Date().toISOString(),element:document.getElementById('element').value,mode:currentMode,count:requestedCount,index,correct,quizIds:quiz.map(getQuestionKey),marked:[...markedQuestions],answered:[...answeredQuestions],answers:[...userAnswers.entries()]};localStorage.setItem(SAVE_KEY,JSON.stringify(session));if(showAlert)alert('Study session saved on this browser.')} 
function getSavedSession(){try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'null')}catch(e){return null}}
function updateResumeBox(){const box=document.getElementById('resumeBox');if(!box)return;const s=getSavedSession();if(!s){box.style.display='none';return}box.style.display='block';const answered=s.answered?s.answered.length:0;box.innerHTML=`<h3>Saved Session</h3><p>${s.mode==='study'?'Study':'Test'} Mode • Question ${(s.index||0)+1} of ${s.count||'?'} • ${answered} answered</p><button onclick="resumeSession()">Resume Session</button><button onclick="clearSavedSession()">Clear Saved Session</button>`}
function resumeSession(){const s=getSavedSession();if(!s||!BANK.length)return;document.getElementById('element').value=s.element||'all';document.getElementById('mode').value=s.mode||'study';document.getElementById('count').value=s.count||35;requestedCount=s.count||35;currentMode=s.mode||'study';const byId=new Map(BANK.map(q=>[getQuestionKey(q),q]));quiz=(s.quizIds||[]).map(id=>byId.get(id)).filter(Boolean);if(!quiz.length)quiz=buildQuizPool(getSelectedPool(),requestedCount);index=Math.min(s.index||0,quiz.length-1);correct=s.correct||0;markedQuestions=new Set(s.marked||[]);answeredQuestions=new Set(s.answered||[]);userAnswers=new Map(s.answers||[]);showQuiz()}
function clearSavedSession(){localStorage.removeItem(SAVE_KEY);updateResumeBox()}
function newSession(){document.getElementById('quiz').style.display='none';document.getElementById('results').style.display='none';setSetupVisible(true);updateQuestionStatus()}
function getMissedQuestionIndexes(){return quiz.map((q,i)=>userAnswers.get(i)===q.answer?null:i).filter(i=>i!==null)}
function getMarkedQuestionIndexes(){return quiz.map((q,i)=>markedQuestions.has(getQuestionKey(q))?i:null).filter(i=>i!==null)}
function getReviewQuestionIndexes(){return [...new Set([...getMissedQuestionIndexes(),...getMarkedQuestionIndexes()])]}
function getReviewReason(i){const q=quiz[i];const missed=userAnswers.get(i)!==q.answer;const marked=markedQuestions.has(getQuestionKey(q));if(missed&&marked)return'Missed + Marked';if(missed)return'Missed';return'Marked'}
function getReviewClass(i){const q=quiz[i];const missed=userAnswers.get(i)!==q.answer;const marked=markedQuestions.has(getQuestionKey(q));if(missed)return'review-missed';if(marked)return'review-marked';return''}
function renderReviewAnswers(q,selected){return ['A','B','C','D'].map(letter=>{let classes='review-answer';if(letter===q.answer)classes+=' review-correct';if(letter===selected&&selected!==q.answer)classes+=' review-wrong';if(letter===selected)classes+=' review-selected';return`<div class="${classes}"><span class="review-letter">${letter}</span><span>${q.options[letter]}</span></div>`}).join('')}
function renderReview(){const results=document.getElementById('results');if(!reviewIndexes.length){results.innerHTML='<div class="review-shell"><h2>Review Test</h2><p>No missed or marked questions to review.</p><button onclick="showResults()">Back to Results</button><button onclick="newSession()">New Session</button></div>';return}const sourceIndex=reviewIndexes[reviewIndex];const q=quiz[sourceIndex];const selected=userAnswers.get(sourceIndex);const selectedText=selected?`${selected}. ${q.options[selected]}`:'Unanswered';const missedIndexes=getMissedQuestionIndexes();const markedIndexes=getMarkedQuestionIndexes();const missedQuestions=missedIndexes.map(i=>quiz[i]);const reviewQuestions=reviewIndexes.map(i=>quiz[i]);results.innerHTML=`<div class="review-shell"><div class="review-header"><div><h2>Review Test</h2><p>Question ${reviewIndex+1} of ${reviewIndexes.length}</p></div><div class="review-stats"><span>${missedIndexes.length} missed</span><span>${markedIndexes.length} marked</span></div></div><div class="review-card-large ${getReviewClass(sourceIndex)}"><div class="review-meta"><b>${q.id}</b><span>${getReviewReason(sourceIndex)}</span></div><p class="review-question">${q.question}</p><div class="review-answer-summary"><div><b>Your answer</b><br>${selectedText}</div><div><b>Correct answer</b><br>${q.answer}. ${q.options[q.answer]}</div></div><div class="review-answer-list">${renderReviewAnswers(q,selected)}</div></div><div class="review-nav"><button onclick="previousReviewQuestion()" ${reviewIndex===0?'disabled':''}>Previous</button><button onclick="nextReviewQuestion()" ${reviewIndex>=reviewIndexes.length-1?'disabled':''}>Next</button></div><div class="review-actions"><button onclick="retestMissedQuestions()" ${missedQuestions.length?'':'disabled'}>Retest Missed Only (${missedQuestions.length})</button><button onclick="retestMissedMarkedQuestions()" ${reviewQuestions.length?'':'disabled'}>Retest Missed + Marked (${reviewQuestions.length})</button><button onclick="showResults()">Back to Results</button><button onclick="newSession()">New Session</button></div></div>`}
function reviewTest(){reviewIndexes=getReviewQuestionIndexes();reviewIndex=0;document.getElementById('quiz').style.display='none';document.getElementById('results').style.display='block';setSetupVisible(false);renderReview()}
function previousReviewQuestion(){if(reviewIndex<=0)return;reviewIndex--;renderReview()}
function nextReviewQuestion(){if(reviewIndex>=reviewIndexes.length-1)return;reviewIndex++;renderReview()}
function retestMissedQuestions(){const questions=getMissedQuestionIndexes().map(i=>quiz[i]);startCustomQuiz(questions,'test')}
function retestMissedMarkedQuestions(){const questions=getReviewQuestionIndexes().map(i=>quiz[i]);startCustomQuiz(questions,'test')}
function showResults(){finishQuiz()}
function finishQuiz(){saveSession(false);const pct=Math.round(correct/quiz.length*100);const missedCount=getMissedQuestionIndexes().length;const markedCount=getMarkedQuestionIndexes().length;const reviewCount=getReviewQuestionIndexes().length;document.getElementById('quiz').style.display='none';document.getElementById('results').style.display='block';setSetupVisible(false);document.getElementById('results').innerHTML=`<h2>Results</h2><p><b>Mode:</b> ${currentMode==='study'?'Study':'Test'}</p><p><b>Score:</b> ${pct}%</p><p><b>Correct:</b> ${correct} / ${quiz.length}</p><p><b>Missed:</b> ${missedCount}</p><p><b>Marked:</b> ${markedCount}</p><p><b>Status:</b> ${pct>=74?'PASSING':'NOT PASSING'}</p>${reviewCount?`<button onclick="reviewTest()">Review Missed + Marked Questions (${reviewCount})</button>`:''}${missedCount?`<button onclick="retestMissedQuestions()">Retest Missed Only (${missedCount})</button>`:''}${reviewCount?`<button onclick="retestMissedMarkedQuestions()">Retest Missed + Marked (${reviewCount})</button>`:''}<button onclick="newSession()">New Session</button><button onclick="clearSavedSession()">Clear Saved Session</button>`}
initApp();
