const SAVE_KEY='fcc_prep_saved_session_v1';
let BANK=[];let quiz=[];let index=0;let correct=0;let requestedCount=0;let currentMode='study';let markedQuestions=new Set();let answeredQuestions=new Set();let userAnswers=new Map();
function shuffle(arr){return[...arr].sort(()=>Math.random()-.5)}
function getSelectedPool(){const e=document.getElementById('element').value;return BANK.filter(q=>e==='all'||q.element===e)}
function getSelectedElementLabel(){const s=document.getElementById('element');return s.options[s.selectedIndex].text}
function setSetupVisible(visible){const setup=document.querySelector('.setup-card:not(#resumeBox)');const resume=document.getElementById('resumeBox');const status=document.getElementById('questionStatus');if(setup)setup.style.display=visible?'block':'none';if(resume&&visible)updateResumeBox();if(resume&&!visible)resume.style.display='none';if(status)status.style.display=visible?'block':'none'}
function updateQuestionStatus(){const status=document.getElementById('questionStatus');if(!BANK.length){status.innerText='Loading questions...';return}const selectedPool=getSelectedPool();status.innerText=`${getSelectedElementLabel()}: ${selectedPool.length} questions available (${BANK.length} total loaded)`}
async function initApp(){const status=document.getElementById('questionStatus');try{BANK=await loadQuestionPool();updateQuestionStatus();document.getElementById('startBtn').disabled=false;updateResumeBox()}catch(error){console.error(error);status.innerText='Question data failed to load.'}}
function buildQuizPool(pool,count){if(!pool.length)return[];let output=[];while(output.length<count)output=output.concat(shuffle(pool));return output.slice(0,count)}
function startQuiz(){if(!BANK.length){alert('Question data is still loading. Please try again.');return}requestedCount=parseInt(document.getElementById('count').value,10)||35;currentMode=document.getElementById('mode').value;quiz=buildQuizPool(getSelectedPool(),requestedCount);index=0;correct=0;markedQuestions=new Set();answeredQuestions=new Set();userAnswers=new Map();showQuiz()}
function showQuiz(){setSetupVisible(false);document.getElementById('results').style.display='none';document.getElementById('quiz').style.display='grid';document.getElementById('sidebarTitle').innerText=`${quiz.length} questions`;document.getElementById('scoreLine').style.display=currentMode==='study'?'flex':'none';renderQuestion()}
function getQuestionKey(q){return q.id||`${q.element}-${q.question}`}
function isMarkedCurrent(){return quiz.length&&markedQuestions.has(getQuestionKey(quiz[index]))}
function canMoveNext(){return answeredQuestions.has(index)||isMarkedCurrent()}
function updateSidebar(){const nav=document.getElementById('questionNav');nav.innerHTML='';quiz.forEach((q,i)=>{const key=getQuestionKey(q);const btn=document.createElement('button');btn.className='nav-question';btn.innerText=`Question ${i+1}`;if(i===index)btn.classList.add('current');if(markedQuestions.has(key))btn.classList.add('marked');if(answeredQuestions.has(i))btn.classList.add(userAnswers.get(i)===q.answer?'answered-correct':'answered-incorrect');btn.onclick=()=>{if(currentMode!=='study')return;index=i;renderQuestion()};nav.appendChild(btn)});const answered=answeredQuestions.size;const remaining=quiz.length-answered;const score=answered?Math.round(correct/answered*100):0;document.getElementById('answeredCount').innerText=answered;document.getElementById('remainingCount').innerText=remaining;document.getElementById('markedCount').innerText=markedQuestions.size;document.getElementById('sidebarScore').innerText=answered?`${score}%`:'--'}
function updateLiveScore(){const liveScore=document.getElementById('liveScore');if(currentMode!=='study'){liveScore.innerText='';return}const answered=answeredQuestions.size;const pct=answered?Math.round(correct/answered*100):0;liveScore.innerText=answered?`Study score: ${pct}% (${correct}/${answered}) - ${pct>=74?'PASSING':'NOT PASSING'}`:'Study score: no answers yet'}
function renderQuestion(){const q=quiz[index];const key=getQuestionKey(q);document.getElementById('progress').innerText=`Question ${index+1} of ${quiz.length}`;document.getElementById('qid').innerText=q.id;document.getElementById('question').innerText=q.question;const options=document.getElementById('options');options.innerHTML='';['A','B','C','D'].forEach(letter=>{const row=document.createElement('button');row.className='answer-row';row.innerHTML=`<span class="answer-letter">${letter}</span><span>${q.options[letter]}</span>`;if(answeredQuestions.has(index)){row.disabled=true;const selected=userAnswers.get(index);if(currentMode==='study'){if(letter===q.answer)row.classList.add('correct');if(letter===selected&&selected!==q.answer)row.classList.add('wrong')}}row.onclick=()=>answerQuestion(letter,row,q);options.appendChild(row)});document.getElementById('markBtn').innerText=markedQuestions.has(key)?'Unmark':'Mark';document.getElementById('prevBtn').disabled=currentMode!=='study'||index===0;document.getElementById('nextBtn').disabled=!canMoveNext();updateSidebar();updateLiveScore();saveSession(false)}
function answerQuestion(letter,btn,q){if(answeredQuestions.has(index))return;answeredQuestions.add(index);userAnswers.set(index,letter);if(letter===q.answer)correct++;document.querySelectorAll('.answer-row').forEach(x=>x.disabled=true);if(currentMode==='study'){if(letter===q.answer)btn.classList.add('correct');else{btn.classList.add('wrong');document.querySelectorAll('.answer-row').forEach(x=>{if(x.innerText.trim().startsWith(q.answer))x.classList.add('correct')})}}document.getElementById('nextBtn').disabled=false;updateSidebar();updateLiveScore();saveSession(false)}
function toggleMarkedQuestion(){const q=quiz[index];const key=getQuestionKey(q);if(markedQuestions.has(key))markedQuestions.delete(key);else markedQuestions.add(key);renderQuestion();saveSession(false)}
function previousQuestion(){if(currentMode!=='study'||index<=0)return;index--;renderQuestion()}
function nextQuestion(){if(!canMoveNext())return;index++;if(index>=quiz.length){finishQuiz();return}renderQuestion()}
function saveSession(showAlert=true){if(!quiz.length)return;const session={savedAt:new Date().toISOString(),element:document.getElementById('element').value,mode:currentMode,count:requestedCount,index,correct,quizIds:quiz.map(getQuestionKey),marked:[...markedQuestions],answered:[...answeredQuestions],answers:[...userAnswers.entries()]};localStorage.setItem(SAVE_KEY,JSON.stringify(session));if(showAlert)alert('Study session saved on this browser.')} 
function getSavedSession(){try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'null')}catch(e){return null}}
function updateResumeBox(){const box=document.getElementById('resumeBox');if(!box)return;const s=getSavedSession();if(!s){box.style.display='none';return}box.style.display='block';const answered=s.answered?s.answered.length:0;box.innerHTML=`<h3>Saved Session</h3><p>${s.mode==='study'?'Study':'Test'} Mode • Question ${(s.index||0)+1} of ${s.count||'?'} • ${answered} answered</p><button onclick="resumeSession()">Resume Session</button><button onclick="clearSavedSession()">Clear Saved Session</button>`}
function resumeSession(){const s=getSavedSession();if(!s||!BANK.length)return;document.getElementById('element').value=s.element||'all';document.getElementById('mode').value=s.mode||'study';document.getElementById('count').value=s.count||35;requestedCount=s.count||35;currentMode=s.mode||'study';const byId=new Map(BANK.map(q=>[getQuestionKey(q),q]));quiz=(s.quizIds||[]).map(id=>byId.get(id)).filter(Boolean);if(!quiz.length)quiz=buildQuizPool(getSelectedPool(),requestedCount);index=Math.min(s.index||0,quiz.length-1);correct=s.correct||0;markedQuestions=new Set(s.marked||[]);answeredQuestions=new Set(s.answered||[]);userAnswers=new Map(s.answers||[]);showQuiz()}
function clearSavedSession(){localStorage.removeItem(SAVE_KEY);updateResumeBox()}
function newSession(){document.getElementById('quiz').style.display='none';document.getElementById('results').style.display='none';setSetupVisible(true);updateQuestionStatus()}
function finishQuiz(){saveSession(false);const pct=Math.round(correct/quiz.length*100);document.getElementById('quiz').style.display='none';document.getElementById('results').style.display='block';setSetupVisible(false);document.getElementById('results').innerHTML=`<h2>Results</h2><p><b>Mode:</b> ${currentMode==='study'?'Study':'Test'}</p><p><b>Score:</b> ${pct}%</p><p><b>Correct:</b> ${correct} / ${quiz.length}</p><p><b>Marked:</b> ${markedQuestions.size}</p><p><b>Status:</b> ${pct>=74?'PASSING':'NOT PASSING'}</p><button onclick="newSession()">New Session</button><button onclick="clearSavedSession()">Clear Saved Session</button>`}
initApp();